import { siteConfig } from './site-config';

const now = '2026-03-16T00:00:00.000Z';

export const SAMPLE_CATEGORIES = [
  {
    id: 1,
    name: 'Quartz Capsule Line',
    slug: 'healing-crystal-jewelry',
    path: '/products/healing-crystal-jewelry',
    level: 0,
    description: 'Mock category for textured stone bracelets, pendants, and display-ready capsule sets.',
    imageUrl: siteConfig.scenePlaceholder,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: 2,
    name: 'Silver Studio Line',
    slug: '925-silver-crystal-jewelry',
    path: '/products/925-silver-crystal-jewelry',
    level: 0,
    description: 'Mock category for plated silver silhouettes, adjustable settings, and gift-ready samples.',
    imageUrl: siteConfig.scenePlaceholder,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: 3,
    name: 'Mindful Ritual Edit',
    slug: 'chakra-yoga-jewelry',
    path: '/products/chakra-yoga-jewelry',
    level: 0,
    description: 'Mock assortment for wellness-themed bracelets and pendants with soft storytelling copy.',
    imageUrl: siteConfig.scenePlaceholder,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: 4,
    name: 'Aroma Companion Series',
    slug: 'aromatherapy-jewelry',
    path: '/products/aromatherapy-jewelry',
    level: 0,
    description: 'Mock category for diffuser-ready accessories and private-label starter packs.',
    imageUrl: siteConfig.scenePlaceholder,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
];

function placeholderGallery(label: string) {
  return [
    { url: siteConfig.productPlaceholder, alt: `${label} hero mock image` },
    { url: siteConfig.productPlaceholder, alt: `${label} detail mock image` },
  ];
}

export const SAMPLE_PRODUCTS = [
  {
    name: 'Mock Quartz Bracelet Alpha',
    slug: 'mock-quartz-bracelet-alpha',
    excerpt: 'Placeholder bracelet listing for demo storefront presentation.',
    description:
      'Mock product copy for a quartz-inspired bracelet. Replace this text with your own merchandising story, material details, and target buyer notes.',
    price: 12.5,
    priceCurrency: 'USD',
    categoryId: 1,
    imageUrl: siteConfig.productPlaceholder,
    moq: 'MOQ 12 units',
    leadTime: '5-7 business days',
    material: 'Mock quartz, plated brass, stretch cord',
    certifications: ['Demo material certificate'],
    customizationOptions: ['Private label card', 'Gift pouch', 'Color variation'],
    tags: ['mock', 'quartz', 'bracelet'],
    gallery: placeholderGallery('Mock Quartz Bracelet Alpha'),
  },
  {
    name: 'Mock Quartz Pendant Beta',
    slug: 'mock-quartz-pendant-beta',
    excerpt: 'Placeholder pendant with catalog-friendly naming and generic value props.',
    description:
      'Use this mock pendant entry to demonstrate how a hero product can look before your real catalog is loaded.',
    price: 16,
    priceCurrency: 'USD',
    categoryId: 1,
    imageUrl: siteConfig.productPlaceholder,
    moq: 'MOQ 10 units',
    leadTime: '7-10 business days',
    material: 'Mock stone, alloy setting, adjustable chain',
    certifications: ['Demo compliance sheet'],
    customizationOptions: ['Custom charm card', 'Hangtag swap'],
    tags: ['mock', 'pendant'],
    gallery: placeholderGallery('Mock Quartz Pendant Beta'),
  },
  {
    name: 'Studio Silver Bracelet One',
    slug: 'studio-silver-bracelet-one',
    excerpt: 'Placeholder silver bracelet for private-label demonstrations.',
    description:
      'Mock content that shows how to describe finish, sizing, and packaging without exposing any client-specific catalog data.',
    price: 19,
    priceCurrency: 'USD',
    categoryId: 2,
    imageUrl: siteConfig.productPlaceholder,
    moq: 'MOQ 8 units',
    leadTime: '10-12 business days',
    material: 'Sterling silver finish, cubic zirconia accents',
    certifications: ['Demo plating report'],
    customizationOptions: ['Logo card', 'Engraving-ready tag'],
    tags: ['mock', 'silver', 'bracelet'],
    gallery: placeholderGallery('Studio Silver Bracelet One'),
  },
  {
    name: 'Studio Silver Pendant Two',
    slug: 'studio-silver-pendant-two',
    excerpt: 'Placeholder pendant listing with neutral merchandising language.',
    description:
      'Generic product copy for a plated silver pendant that can be replaced by your live assortment later.',
    price: 22,
    priceCurrency: 'USD',
    categoryId: 2,
    imageUrl: siteConfig.productPlaceholder,
    moq: 'MOQ 8 units',
    leadTime: '10-12 business days',
    material: 'Silver-tone alloy, faceted insert',
    certifications: ['Demo plating report'],
    customizationOptions: ['Chain length swap', 'Card insert update'],
    tags: ['mock', 'silver', 'pendant'],
    gallery: placeholderGallery('Studio Silver Pendant Two'),
  },
  {
    name: 'Mindful Stack Bracelet Set',
    slug: 'mindful-stack-bracelet-set',
    excerpt: 'Placeholder wellness set for template previews and collection demos.',
    description:
      'Example copy for a wellness-themed bracelet stack. Replace the narrative, stones, and benefits with your own approved messaging.',
    price: 14,
    priceCurrency: 'USD',
    categoryId: 3,
    imageUrl: siteConfig.productPlaceholder,
    moq: 'MOQ 15 units',
    leadTime: '6-8 business days',
    material: 'Mixed resin beads, plated spacer set',
    certifications: ['Demo product sheet'],
    customizationOptions: ['Story card', 'Retail-ready bundle'],
    tags: ['mock', 'wellness', 'set'],
    gallery: placeholderGallery('Mindful Stack Bracelet Set'),
  },
  {
    name: 'Mindful Pendant Loop',
    slug: 'mindful-pendant-loop',
    excerpt: 'Placeholder pendant with meditation-inspired positioning.',
    description:
      'Sample storefront copy for a pendant product page. This entry exists only to keep the template visually complete.',
    price: 15.5,
    priceCurrency: 'USD',
    categoryId: 3,
    imageUrl: siteConfig.productPlaceholder,
    moq: 'MOQ 10 units',
    leadTime: '6-8 business days',
    material: 'Enamel pendant, adjustable cord',
    certifications: ['Demo product sheet'],
    customizationOptions: ['Color card', 'Packaging note'],
    tags: ['mock', 'pendant', 'wellness'],
    gallery: placeholderGallery('Mindful Pendant Loop'),
  },
  {
    name: 'Aroma Clip Diffuser Charm',
    slug: 'aroma-clip-diffuser-charm',
    excerpt: 'Placeholder diffuser charm for demo aromatherapy collections.',
    description:
      'Generic copy for an aroma accessory product. Use it to demo card layout, pricing blocks, and CTA structure.',
    price: 13,
    priceCurrency: 'USD',
    categoryId: 4,
    imageUrl: siteConfig.productPlaceholder,
    moq: 'MOQ 20 units',
    leadTime: '5-7 business days',
    material: 'Porous stone insert, plated clip',
    certifications: ['Demo accessory sheet'],
    customizationOptions: ['Oil color insert', 'Private label sleeve'],
    tags: ['mock', 'aroma', 'diffuser'],
    gallery: placeholderGallery('Aroma Clip Diffuser Charm'),
  },
  {
    name: 'Aroma Pendant Capsule',
    slug: 'aroma-pendant-capsule',
    excerpt: 'Placeholder pendant capsule for starter-kit merchandising.',
    description:
      'Mock product description for a diffuser pendant capsule. Replace this placeholder once your approved assortment is ready.',
    price: 17.5,
    priceCurrency: 'USD',
    categoryId: 4,
    imageUrl: siteConfig.productPlaceholder,
    moq: 'MOQ 12 units',
    leadTime: '7-9 business days',
    material: 'Plated brass, absorbent core insert',
    certifications: ['Demo accessory sheet'],
    customizationOptions: ['Chain finish', 'Instruction card'],
    tags: ['mock', 'aroma', 'pendant'],
    gallery: placeholderGallery('Aroma Pendant Capsule'),
  },
];
