export const siteConfig = {
  templateMode: true,
  enableAnalytics: false,
  templateTurnstileToken: 'template-turnstile-token',
  turnstileSiteKey: 'mock-turnstile-site-key',
  turnstileSecretKey: 'mock-turnstile-secret-key',
  brandName: 'Template Company Placeholder',
  legalName: 'Template Company Legal Placeholder',
  shortName: 'Template Company',
  websiteUrl: 'https://template-site-placeholder.example',
  websiteHost: 'template-site-placeholder.example',
  apiBaseUrl: 'https://template-site-placeholder.example/api',
  strapiBaseUrl: 'https://cms.template-site-placeholder.example',
  assetHost: 'assets.template-site-placeholder.example',
  mediaHost: 'media.template-site-placeholder.example',
  r2DevHost: 'template-site-placeholder.r2.dev',
  contactEmail: 'contact@template-site-placeholder.example',
  adminEmail: 'admin@template-site-placeholder.example',
  encodedContactEmail: 'Y29udGFjdEB0ZW1wbGF0ZS1zaXRlLXBsYWNlaG9sZGVyLmV4YW1wbGU=',
  contactPhoneDisplay: '+00 0000 0000',
  contactPhoneHref: '+00000000000',
  encodedContactPhone: 'KzAwIDAwMDAgMDAwMA==',
  whatsappLabel: 'Template Contact Placeholder',
  wechatId: 'template_contact_placeholder',
  addressLines: ['Template Address Line 1', 'Template Address Line 2'],
  businessHours: 'Replace with approved support hours before publishing',
  catalogCta: 'Open Template Contact',
  companyDescription:
    'This demo site uses mock company names, contact details, domain data, legal text, and imagery. Replace all placeholder content before publishing.',
  productPlaceholder: '/placeholders/product-card.svg',
  scenePlaceholder: '/placeholders/catalog-scene.svg',
  logoPath: '/logos/template-logo.svg',
  templateCopyLabel: '可发布前自行替换的模板文案',
  templateCopyDescription:
    'All visible company names, contact information, domain details, imagery, legal text, and promises on this site are mock data to replace before publishing.',
  placeholderLastModified: '2026-01-01T00:00:00.000Z',
  googleClientId: 'mock-google-client-id.apps.googleusercontent.com',
  googleClientSecret: 'mock-google-client-secret',
  betterAuthSecret: 'mock-better-auth-secret',
  gaMeasurementId: 'G-TEMPLATE0000',
  googleAdsId: 'AW-TEMPLATE0000',
  googleAdsInquiryLabel: 'template_inquiry_label',
  googleAdsFeedUsername: 'template-feed-user',
  googleAdsFeedPassword: 'template-feed-password',
  placeholderMetrics: {
    products: {
      total: 12,
      active: 8,
      inactive: 4,
      avgPrice: 19.9,
    },
    posts: {
      total: 6,
      published: 4,
      draft: 2,
    },
    contacts: 3,
  },
  dbName: 'template_site_placeholder',
  r2BucketName: 'template-site-placeholder-assets',
  workerName: 'template-site-placeholder-app',
  kvNamespaceId: 'your-cache-namespace-id',
  databaseId: 'your-d1-database-id',
  cloudflareAccountId: 'your-cloudflare-account-id',
  demoChatMessage:
    'Hello, I am reviewing this template site and need the placeholder contact flow.',
} as const;
