-- 模板版 D1 商品种子数据
-- 所有内容均为 mock data，发布前请替换

DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `name` text NOT NULL,
  `slug` text NOT NULL,
  `description` text,
  `price` real,
  `category_id` integer,
  `image_url` text,
  `material` text,
  `moq` text,
  `lead_time` text,
  `attributes` text,
  `sku_variants` text,
  `images` text,
  `is_active` integer DEFAULT 1,
  `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE set null
);

CREATE UNIQUE INDEX IF NOT EXISTS `products_slug_unique` ON `products` (`slug`);

INSERT INTO `products` (
  `id`,
  `name`,
  `slug`,
  `description`,
  `price`,
  `category_id`,
  `image_url`,
  `material`,
  `moq`,
  `lead_time`,
  `attributes`,
  `sku_variants`,
  `images`,
  `is_active`,
  `created_at`,
  `updated_at`
) VALUES
  (
    1,
    'Template Bracelet Alpha',
    'template-bracelet-alpha',
    '模板商品说明，用于演示商品列表、详情页与询盘流程。请在发布前替换为真实商品资料。',
    12.5,
    1,
    '/placeholders/product-card.svg',
    'Mock alloy, elastic cord',
    'MOQ 12 units',
    '5-7 business days',
    '{"notes":"Template data only","tags":["template","bracelet"]}',
    '[{"name":"Template SKU A","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Bracelet Alpha"}]',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    2,
    'Template Pendant Beta',
    'template-pendant-beta',
    '占位商品数据，用于验证数据库、后台和前台的字段映射。',
    16.0,
    1,
    '/placeholders/product-card.svg',
    'Mock stone, alloy setting',
    'MOQ 10 units',
    '7-9 business days',
    '{"notes":"Template data only","tags":["template","pendant"]}',
    '[{"name":"Template SKU B","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Pendant Beta"}]',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    3,
    'Template Silver Bracelet Gamma',
    'template-silver-bracelet-gamma',
    '后台演示商品，用来检查价格、属性、图片和变体字段的展示效果。',
    19.0,
    2,
    '/placeholders/product-card.svg',
    'Silver-tone finish, cubic accents',
    'MOQ 8 units',
    '10-12 business days',
    '{"notes":"Template data only","tags":["template","silver","bracelet"]}',
    '[{"name":"Template SKU C","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Silver Bracelet Gamma"}]',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    4,
    'Template Silver Pendant Delta',
    'template-silver-pendant-delta',
    '这是一条可替换的 mock 商品文案，用于保持模板数据库在演示阶段可用。',
    22.0,
    2,
    '/placeholders/product-card.svg',
    'Silver-tone alloy, chain set',
    'MOQ 8 units',
    '10-12 business days',
    '{"notes":"Template data only","tags":["template","silver","pendant"]}',
    '[{"name":"Template SKU D","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Silver Pendant Delta"}]',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    5,
    'Template Wellness Set Epsilon',
    'template-wellness-set-epsilon',
    '占位套装商品，用于展示多品类场景下的后台数据结构与筛选逻辑。',
    14.0,
    3,
    '/placeholders/product-card.svg',
    'Mixed resin beads, plated spacers',
    'MOQ 15 units',
    '6-8 business days',
    '{"notes":"Template data only","tags":["template","set","wellness"]}',
    '[{"name":"Template SKU E","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Wellness Set Epsilon"}]',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    6,
    'Template Mindful Pendant Zeta',
    'template-mindful-pendant-zeta',
    '模板吊坠样例，方便在导入数据库后验证字段映射、后台编辑和前台读取。',
    15.5,
    3,
    '/placeholders/product-card.svg',
    'Mock enamel pendant, cord',
    'MOQ 10 units',
    '6-8 business days',
    '{"notes":"Template data only","tags":["template","pendant","wellness"]}',
    '[{"name":"Template SKU F","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Mindful Pendant Zeta"}]',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    7,
    'Template Diffuser Charm Eta',
    'template-diffuser-charm-eta',
    '演示用配件商品，展示占位图片、占位价格和占位属性的完整数据链路。',
    13.0,
    4,
    '/placeholders/product-card.svg',
    'Porous insert, plated clip',
    'MOQ 20 units',
    '5-7 business days',
    '{"notes":"Template data only","tags":["template","diffuser","accessory"]}',
    '[{"name":"Template SKU G","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Diffuser Charm Eta"}]',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    8,
    'Template Capsule Theta',
    'template-capsule-theta',
    '这是模板种子脚本中的样例数据，用于确认后台导入后可正常浏览和替换。',
    17.5,
    4,
    '/placeholders/product-card.svg',
    'Plated brass, absorbent insert',
    'MOQ 12 units',
    '7-9 business days',
    '{"notes":"Template data only","tags":["template","capsule","accessory"]}',
    '[{"name":"Template SKU H","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Capsule Theta"}]',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );
