
-- 纯净版 D1 数据库 61 款商品补录脚本，字段对齐正确版 src/drizzle/schema.ts
DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `name` text NOT NULL,
  `slug` text NOT NULL,
  `description` text,
  `price` real,
  `category_id` integer,
  `image_url` text,
  `material` text,
  `moq` text,
  `lead_time` text,
  `attributes` text,
  `sku_variants` text,
  `images` text,
  `is_active` integer DEFAULT 1,
  `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE set null
);

CREATE UNIQUE INDEX IF NOT EXISTS `products_slug_unique` ON `products` (`slug`);

INSERT INTO `products` (
  `id`, `name`, `slug`, `description`, `price`, `category_id`, `image_url`,
  `material`, `moq`, `lead_time`, `attributes`, `sku_variants`, `images`, `is_active`,
  `created_at`, `updated_at`
) VALUES 
  (1, 'Rose Quartz Healing Bracelet', 'rose-quartz-healing-bracelet', 'This beautiful rose quartz bracelet features 8mm natural rose quartz beads, known as the "stone of love." Each bracelet is carefully handcrafted with high-quality elastic cord, ensuring durability and comfort. Rose quartz is believed to promote self-love, compassion, and emotional healing. Perfect for retailers looking to offer high-quality healing crystal jewelry to their customers.', 8.5, 1, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800', 'Natural Rose Quartz, Elastic Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Custom bead size (6mm, 8mm, 10mm)","Add silver charms","Custom packaging with your logo (MOQ 1000 pcs)"],"tags":["rose-quartz","bracelet","healing","love"]}', NULL, '[{"url":"https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800","alt":"Rose Quartz Bracelet View 1"},{"url":"https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800","alt":"Rose Quartz Bracelet View 2"},{"url":"https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800","alt":"Rose Quartz Bracelet View 3"}]', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'Amethyst Protection Bracelet', 'amethyst-protection-bracelet', 'Premium quality amethyst bracelet featuring 8mm natural amethyst beads. Amethyst is known as the stone of spiritual protection, promoting mental clarity and inner peace. This bracelet is perfect for meditation and spiritual practices.', 9, 1, 'https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800', 'Natural Amethyst, Elastic Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Custom bead size (6mm, 8mm, 10mm)","Add silver charms"],"tags":["amethyst","bracelet","protection","spiritual"]}', NULL, '[{"url":"https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800","alt":"Amethyst Bracelet View 1"}]', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'Black Tourmaline Grounding Bracelet', 'black-tourmaline-grounding-bracelet', 'Black tourmaline bracelet designed for grounding and electromagnetic field (EMF) protection. Black tourmaline is a powerful protective stone that promotes stability and grounding energy.', 7.5, 1, 'https://images.unsplash.com/photo-1630019329416-5a6f0b8d9e3f?w=800', 'Natural Black Tourmaline, Elastic Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Custom bead size (6mm, 8mm, 10mm)"],"tags":["black-tourmaline","bracelet","protection","grounding"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (4, 'Clear Quartz Energy Bracelet', 'clear-quartz-energy-bracelet', 'Clear quartz is known as the master healer stone. This bracelet amplifies energy and is perfect for those seeking clarity and positive energy. Ideal for daily wear and meditation.', 8, 1, 'https://images.unsplash.com/photo-1611652022419-a9419f74343b?w=800', 'Natural Clear Quartz, Elastic Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Custom bead size (6mm, 8mm, 10mm)"],"tags":["clear-quartz","bracelet","energy","healing"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (5, 'Amethyst Crystal Pendant Necklace', 'amethyst-pendant-necklace', 'Beautiful amethyst crystal pendant set in sterling silver. This elegant piece combines luxury with spiritual healing properties. Perfect for gift-giving and personal spiritual practice.', 12.5, 1, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 'Natural Amethyst, 925 Sterling Silver, Silver Chain', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate","925 Sterling Silver Verification"],"customizationOptions":["Adjustable chain length","Custom packaging with your logo"],"tags":["amethyst","necklace","pendant","sterling-silver"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (6, 'Rose Quartz Heart Necklace', 'rose-quartz-heart-necklace', 'This stunning heart-shaped rose quartz pendant is a symbol of unconditional love and compassion. Perfect for those seeking to attract love and deepen their relationships.', 11, 1, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800', 'Natural Rose Quartz, 925 Sterling Silver Chain', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Adjustable chain"],"tags":["rose-quartz","necklace","pendant","love"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (7, 'Crystal Quartz Point Necklace', 'crystal-quartz-point-necklace', 'Raw crystal quartz point necklace for those serious about energy work and crystal healing. The natural point shape amplifies energy and intention. Premium quality raw crystal.', 13.5, 1, 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=800', 'Raw Natural Clear Quartz, Adjustable Leather Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Leather or chain option"],"tags":["clear-quartz","necklace","raw","energy-work"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (8, 'Moonstone 925 Silver Bracelet', 'moonstone-silver-bracelet', 'Premium moonstone bracelet featuring genuine 925 sterling silver components. Moonstone is known for its connection to intuition and feminine energy. A luxurious addition to any jewelry collection.', 15.5, 2, 'https://images.unsplash.com/photo-1611652022419-a9419f74343b?w=800', 'Natural Moonstone, 925 Sterling Silver', '5 pcs/style', '7-10 days (sampling) + 3-4 weeks (production)', '{"certifications":["925 Sterling Silver Verification","Natural Crystal Certificate"],"customizationOptions":["Custom bead size","Engraving available"],"tags":["moonstone","bracelet","silver","luxury"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (9, 'Labradorite 925 Silver Bracelet', 'labradorite-silver-bracelet', 'Stunning labradorite bracelet featuring the signature labradorescence effect. Combined with premium 925 sterling silver for a sophisticated, luxurious piece. Labradorite is known for promoting intuition and transformation.', 16, 2, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800', 'Natural Labradorite, 925 Sterling Silver', '5 pcs/style', '7-10 days (sampling) + 3-4 weeks (production)', '{"certifications":["925 Sterling Silver Verification","Natural Crystal Certificate"],"customizationOptions":["Custom sizing","Gift packaging"],"tags":["labradorite","bracelet","silver","mystical"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (10, 'Turquoise 925 Silver Necklace', 'turquoise-silver-necklace', 'Authentic natural turquoise pendant set in sterling silver. Turquoise has been prized for centuries for its healing properties and stunning blue-green color. This necklace combines elegance with spiritual significance.', 18.5, 2, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 'Natural Turquoise, 925 Sterling Silver', '5 pcs/style', '7-10 days (sampling) + 3-4 weeks (production)', '{"certifications":["925 Sterling Silver Verification","Natural Crystal Certificate"],"customizationOptions":["Adjustable length","Custom engraving"],"tags":["turquoise","necklace","silver","healing"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (11, 'Opal 925 Silver Pendant', 'opal-silver-pendant', 'Exquisite opal pendant showcasing the unique color play and iridescence that makes opal so special. Set in fine 925 sterling silver for a truly luxurious piece. Opal is known for enhancing creativity and emotional expression.', 20, 2, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800', 'Natural Opal, 925 Sterling Silver', '5 pcs/style', '10-14 days (sampling) + 3-4 weeks (production)', '{"certifications":["925 Sterling Silver Verification","Natural Opal Certificate"],"customizationOptions":["Chain length adjustment","Premium gift box"],"tags":["opal","necklace","silver","luxury"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (12, '7 Chakra Stone Bracelet', '7-chakra-stone-bracelet', 'This complete chakra bracelet features all 7 chakra stones in perfect alignment. Each stone corresponds to a different energy center, making it ideal for yoga practitioners and those interested in chakra healing and balancing.', 6.5, 3, 'https://images.unsplash.com/photo-1603561596112-0a132b757442?w=800', '7 Natural Chakra Stones, Elastic Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate","Chakra Alignment Certified"],"customizationOptions":["Custom stone selection","Adjustable fit"],"tags":["chakra","bracelet","yoga","healing","meditation"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (13, 'Chakra & Lava Stone Bracelet', 'chakra-lava-stone-bracelet', 'Combine chakra healing with aromatherapy! This unique bracelet features chakra stones paired with porous lava beads that absorb and diffuse your favorite essential oils. Perfect for holistic wellness practitioners.', 7, 3, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800', '7 Chakra Stones, Natural Lava Beads, Elastic Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Adjustable size","Essential oil sample included"],"tags":["chakra","lava","bracelet","aromatherapy","healing"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (14, 'Chakra Pendant Necklace', 'chakra-pendant-necklace', 'Beautiful chakra pendant necklace with all 7 chakra stones arranged in an aesthetically pleasing mandala design. Perfect for meditation and chakra balancing work. A spiritual statement piece.', 10.5, 3, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', '7 Natural Chakra Stones, Metal Pendant Frame, Adjustable Chain', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Chain length adjustment","Chakra stone selection"],"tags":["chakra","necklace","pendant","meditation","spiritual"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (15, 'Om Symbol Chakra Necklace', 'om-chakra-necklace', 'Sacred Om symbol pendant adorned with chakra stone beads. The Om symbol represents the sound of the universe and spiritual vibration. Perfect for yoga practitioners and spiritual seekers.', 11, 3, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800', 'Om Symbol Pendant (Metal), Chakra Stone Beads, Adjustable Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Crystal Certificate"],"customizationOptions":["Cord material choice","Bead selection"],"tags":["om","chakra","necklace","yoga","spiritual"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (16, 'Black Lava Stone Diffuser Bracelet', 'black-lava-diffuser-bracelet', 'Stylish black lava stone bracelet designed for essential oil diffusion. The porous lava beads absorb and hold essential oils, releasing their aroma throughout the day. Perfect for wellness-conscious consumers.', 9, 4, 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800', 'Natural Black Lava Stone, Elastic Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Lava Stone Verified"],"customizationOptions":["Adjustable fit","Essential oil sample pack"],"tags":["lava","bracelet","aromatherapy","diffuser","wellness"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (17, 'White Lava & Chakra Bracelet', 'white-lava-chakra-bracelet', 'Unique two-tone design combining white lava stones with chakra crystal beads. Perfect for those seeking both aromatherapy benefits and chakra balancing. A fusion of two powerful healing practices.', 9.5, 4, 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800', 'White Lava Stone, Chakra Crystal Beads, Elastic Cord', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Lava Stone Verified","Natural Crystal Certificate"],"customizationOptions":["Adjustable size","Chakra selection"],"tags":["lava","chakra","bracelet","aromatherapy","healing"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (18, 'Lava Stone Diffuser Necklace', 'lava-stone-diffuser-necklace', 'Elegant and versatile lava stone pendant necklace for all-day essential oil diffusion. The natural stone texture gives it a rustic, earthy appeal while providing practical aromatherapy benefits. Adjustable length for comfortable wear.', 12, 4, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 'Natural Lava Stone Pendant, Adjustable Chain', '5 pcs/style', '7-10 days (sampling) + 2-3 weeks (production)', '{"certifications":["Natural Lava Stone Verified"],"customizationOptions":["Chain length","Cord or chain material"],"tags":["lava","necklace","aromatherapy","diffuser","pendant"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (19, 'Essential Oil Locket Necklace', 'essential-oil-locket-necklace', 'Vintage-inspired locket necklace featuring a built-in felt pad chamber for essential oil diffusion. This beautiful piece combines fashion with function. Includes felt pads and essential oil sample. Perfect gift for loved ones.', 14.5, 4, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800', 'Metal Locket, Felt Pads, Adjustable Chain', '5 pcs/style', '10-14 days (sampling) + 3-4 weeks (production)', '{"certifications":["Hypoallergenic materials"],"customizationOptions":["Engraving","Premium gift box","Felt pad colors"],"tags":["locket","necklace","aromatherapy","diffuser","gift"]}', NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  