-- 模板商品补录脚本
-- 所有内容均为 mock data，发布前请替换

INSERT OR REPLACE INTO products (
  id,
  name,
  slug,
  description,
  price,
  category_id,
  image_url,
  is_active,
  created_at,
  updated_at,
  material,
  moq,
  lead_time,
  attributes,
  sku_variants,
  images
) VALUES
  (
    20,
    'Template Bracelet Alpha',
    'template-bracelet-alpha',
    '模板商品说明，用于演示后台商品列表、详情和询盘流程。请在发布前替换为真实商品资料。',
    12.5,
    1,
    '/placeholders/product-card.svg',
    1,
    '2026-03-20 09:00:00',
    '2026-03-20 09:00:00',
    'Mock alloy, elastic cord',
    'MOQ 12 units',
    '5-7 business days',
    '{"notes":"Template data only","category":"bracelet"}',
    '[{"name":"Template SKU A","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Bracelet Alpha"}]'
  ),
  (
    21,
    'Template Pendant Beta',
    'template-pendant-beta',
    '占位商品数据，仅用于模板演示。请替换商品标题、卖点、材质、图像与交期。',
    16.0,
    1,
    '/placeholders/product-card.svg',
    1,
    '2026-03-20 09:00:00',
    '2026-03-20 09:00:00',
    'Mock stone, alloy setting',
    'MOQ 10 units',
    '7-9 business days',
    '{"notes":"Template data only","category":"pendant"}',
    '[{"name":"Template SKU B","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Pendant Beta"}]'
  ),
  (
    22,
    'Template Silver Bracelet Gamma',
    'template-silver-bracelet-gamma',
    '后台演示商品，用来检查价格、属性、图片和变体字段的展示效果。',
    19.0,
    2,
    '/placeholders/product-card.svg',
    1,
    '2026-03-20 09:00:00',
    '2026-03-20 09:00:00',
    'Silver-tone finish, cubic accents',
    'MOQ 8 units',
    '10-12 business days',
    '{"notes":"Template data only","category":"silver-bracelet"}',
    '[{"name":"Template SKU C","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Silver Bracelet Gamma"}]'
  ),
  (
    23,
    'Template Silver Pendant Delta',
    'template-silver-pendant-delta',
    '这是一条可替换的 mock 商品文案，用于保持后台和数据库在演示阶段可用。',
    22.0,
    2,
    '/placeholders/product-card.svg',
    1,
    '2026-03-20 09:00:00',
    '2026-03-20 09:00:00',
    'Silver-tone alloy, chain set',
    'MOQ 8 units',
    '10-12 business days',
    '{"notes":"Template data only","category":"silver-pendant"}',
    '[{"name":"Template SKU D","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Silver Pendant Delta"}]'
  ),
  (
    24,
    'Template Wellness Set Epsilon',
    'template-wellness-set-epsilon',
    '占位套装商品，用于展示多品类场景下的后台数据结构与筛选逻辑。',
    14.0,
    3,
    '/placeholders/product-card.svg',
    1,
    '2026-03-20 09:00:00',
    '2026-03-20 09:00:00',
    'Mixed resin beads, plated spacers',
    'MOQ 15 units',
    '6-8 business days',
    '{"notes":"Template data only","category":"wellness-set"}',
    '[{"name":"Template SKU E","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Wellness Set Epsilon"}]'
  ),
  (
    25,
    'Template Mindful Pendant Zeta',
    'template-mindful-pendant-zeta',
    '模板吊坠样例，方便在导入数据库后验证字段映射、后台编辑和前台读取。',
    15.5,
    3,
    '/placeholders/product-card.svg',
    1,
    '2026-03-20 09:00:00',
    '2026-03-20 09:00:00',
    'Mock enamel pendant, cord',
    'MOQ 10 units',
    '6-8 business days',
    '{"notes":"Template data only","category":"mindful-pendant"}',
    '[{"name":"Template SKU F","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Mindful Pendant Zeta"}]'
  ),
  (
    26,
    'Template Diffuser Charm Eta',
    'template-diffuser-charm-eta',
    '演示用配件商品，展示占位图片、占位价格和占位属性的完整数据链路。',
    13.0,
    4,
    '/placeholders/product-card.svg',
    1,
    '2026-03-20 09:00:00',
    '2026-03-20 09:00:00',
    'Porous insert, plated clip',
    'MOQ 20 units',
    '5-7 business days',
    '{"notes":"Template data only","category":"diffuser-charm"}',
    '[{"name":"Template SKU G","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Diffuser Charm Eta"}]'
  ),
  (
    27,
    'Template Capsule Theta',
    'template-capsule-theta',
    '这是模板导入脚本中的最后一条样例数据，用于确认后台批量导入后能正常浏览和替换。',
    17.5,
    4,
    '/placeholders/product-card.svg',
    1,
    '2026-03-20 09:00:00',
    '2026-03-20 09:00:00',
    'Plated brass, absorbent insert',
    'MOQ 12 units',
    '7-9 business days',
    '{"notes":"Template data only","category":"capsule"}',
    '[{"name":"Template SKU H","price":"TBD","stock":"Mock stock"}]',
    '[{"url":"/placeholders/product-card.svg","alt":"Template Capsule Theta"}]'
  );
